properties([
    pipelineTriggers([cron('@hourly')]),
    disableConcurrentBuilds(),
    parameters([
    string(
        defaultValue: 'acharp',
        description: 'Github account',
        name: 'GITACC'),
    string(
        defaultValue: 'jenkins-pipelineTriggers',
        description: 'Github repo',
        name: 'REPO'),
    string(
        defaultValue: 'master',
        description: 'Git Branch',
        name: 'BRANCH')
    ])
    ])

node('master') {
    stage('Run') {
        sh """
            echo "Step 1"
            sleep 5
            echo "Step 2"
        """
    }
}
